services:
  glb_editor:
    build:
      context: .
    env_file: .env
    volumes:
      - ./:/usr/apps/glb_editor
      - ${SOURCE_DIR}:/usr/glb/source
      - ${RESULTS_DIR}:/usr/glb/results
      - ${TEXTURES_DIR}:/usr/glb/textures
    ports: 
      - ${UVICORN_PORT}:9000
    command: [ "uvicorn", "src:app", "--host", "0.0.0.0", "--port", "9000", "--workers", "${UVICORN_WORKERS}" ]